server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fitlife-api

  datasource:
    url: jdbc:mysql://localhost:3306/fitlife_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Chỉ cho phép kiểm tra, KHÔNG tạo bảng

  # SỬA LỖI Ở ĐÂY: flyway phải nằm ngoài jpa
  flyway:
    enabled: true
    baseline-on-migrate: true

cloudinary:
  # SỬA LỖI Ở ĐÂY: Bọc ngoặc kép để YAML hiểu đây là Chuỗi (String), không phải Số
  cloud-name: "dvseaoy5k"
  api-key: "548378961766311"
  api-secret: "GqtAOdXDUzX9sY5Eqg6LWrb_oKU"