server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fitlife-api

  datasource:
    url: jdbc:mysql://localhost:3306/fitlife_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

cloudinary:
  cloud-name: "dvseaoy5k"
  api-key: "548378961766311"
  api-secret: "GqtAOdXDUzX9sY5Eqg6LWrb_oKU"

# Cấu hình Gemini chuẩn xác dựa trên kết quả PowerShell của emmembers
gemini:
  api-key: "AIzaSyACXvlH-Vikni74o0GYj5CSFg1dFs1fOcU"
  # SỬ DỤNG v1beta và gemini-2.5-flash (đúng như danh sách model em list được)
  api-url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"